- name: Executar Gerador de Shorts
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
          BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
        run: |
          cp config.json ../config.json || true
          cp *.ttf ../ 2>/dev/null || true
          python gerar_video.py --feed --envio
